[package]
name = "cftkk"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
serde_json = "1.0"
gctex = { version = "0.3", default-features = false }
png = "0.17.9"
glam = "0.30"

[dependencies]
bitflags = "2.9.0"
